### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nmaslarinos** [compas-dev/compas_libigl#15]
**Installation error: legacy-install-failure**
Trying to install the package as described in the README file, produces a _legacy-install-failure_ error. I 

**To Reproduce**
Simply install the package on a newly created environment, as per the instructions.

**Desktop**
 - OS: [Windows 11]
 - Python version [3.10.8]
 - Python package manager [conda and pip]

**Additional context**
I attach the error message here:
```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\masla\AppData\Local\Temp\pip-req-build-ims7gmgn\setup.py", line 83, in <module>
          setup(
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\command\install.py", line 74, in run
          return orig.install.run(self)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\command\install.py", line 697, in run
          self.run_command('build')
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\masla\anaconda3\envs\gds\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\masla\AppData\Local\Temp\pip-req-build-ims7gmgn\setup.py", line 41, in run
          self.build_extension(ext)
        File "C:\Users\masla\AppData\Local\Temp\pip-req-build-ims7gmgn\setup.py", line 74, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
        File "C:\Users\masla\anaconda3\envs\gds\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\masla\\AppData\\Local\\Temp\\pip-req-build-ims7gmgn', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\masla\\AppData\\Local\\Temp\\pip-req-build-ims7gmgn\\build\\lib.win-amd64-cpython-310', '-DPYTHON_EXECUTABLE=C:\\Users\\masla\\anaconda3\\envs\\gds\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\masla\\AppData\\Local\\Temp\\pip-req-build-ims7gmgn\\build\\lib.win-amd64-cpython-310', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> compas-libigl

note: This is an issue with the package mentioned above, not pip.
```

**Comment by leceta** [comment]
same error here. any solution?
strangely, I managed to install it without problems conda environment with python 3.9 a month ago.

**Comment by tomvanmele** [comment]
i will have a look.
but fyi, we made a few changes to be able to make the package available on conda-forge.
if you don't actually need a dev install, would you mind giving that a try?
it should be available from there for windows, osx, and linux for python 3.8, 3.9, 3.10...

**Comment by tomvanmele** [comment]
i think the problem with the dev install might be that we now use pybind from conda instead of through the git submodules as before. if that is the case, the solution should be as simple as updating the dev install command to
```bash
conda create -n igl-dev python=3.9 git cmake">=3.14" boost eigen=3.3 pybind11
```
and the rest the same as before...

**Comment by tomvanmele** [comment]
note that `eigen=3.3` is only needed to make sure the binding can be installed in the same env as `compas_cgal`. there i have issues getting the code to work with newer versions of `Eigen`. for whatever reason i throws an error whenever i try to assign values to the `Eigen` dense matrix. for example in `compas.cpp` on line 168
```cpp
V(vd, 0) = (double)location[vd][0];
```
if someone can help me figure out why that is the case, we can remove that restriction...

**Comment by tomvanmele** [comment]
new instructions are here: https://compas.dev/compas_libigl
let me know if that doesn't work...

**Comment by tomvanmele** [comment]
@nmaslarinos @leceta ping

**Comment by leceta** [comment]
hi @tomvanmele , sorry for the late response, conda install worked without problems for me. Thank you very much for this amazing tool

**Comment by petrasvestartas** [comment]
I close this issue, since build system has changed.
